#! /bin/sh

sxhkd &
compton -b &
xsetroot -cursor_name left_ptr &
([ -x "$HOME/.fehbg" ] && "$HOME/.fehbg") &
redshift &
([ -x "$(command -v mpd)" ] && mpd) &
([ -x "$(command -v polybar)" ] && sleep 1 && polybar --reload main) &

bspc monitor -d web development communication music

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config normal_border_color  "#665c54"
bspc config active_border_color  "#d5c4a1"
bspc config focused_border_color "#d5c4a1"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
